name: push

on:
  pull_request:  
  push:

jobs:
  ci:
    runs-on: ubuntu-latest        
    steps:
      - uses: actions/checkout@v4

      - name: Upload application (.apk)
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: Application (APK)
          path: "test-data/*.apk"
          if-no-files-found: error
          # compression-level: 0 # already effective an archive, can't really be compressed